### PR TITLE
Added a scraper and updated data till 8/4/2024

### PR DESCRIPTION
**Pull request by alizahidraja**

### CODE REVIEW

**Comment by alizahidraja** [comment]
You can see the dataset I am trying to build here: https://www.kaggle.com/datasets/alizahidraja/quran-nlp

**Comment by MohammedArab1** [comment]
Salam, 

This is really good! And mashAllah at the speed through which you created it!

Unfortunately I don't know if I should merge it at the moment because the generated CSVs are missing information that I'd like to be present. I'd also prefer if the output is JSON instead of CSV as it would allow me to directly import into mongodb, but realistically that's something I could work around.

InshAllah when I have more time I'll be using your work as a starting point to refresh the project. Worst comes to worst I'll use this PR and create V2 API endpoints.

I hope this causes no issues, thanks again!

**Comment by alizahidraja** [comment]
Salam

Thankyou! No worries at all! Do let me know what information is missing, I might need to add it :D

And no worries at all, I hope the notebook helps!

**Comment by alizahidraja** [comment]
Also you can easily convert the CSV to json by using groupby method of pandas, or just use the scraper to add the info

The scraper takes 3 hours to run tho

**Comment by MohammedArab1** [comment]
image

Here are all the fields the API currently returns, some you have whilst others are missing

**Comment by alizahidraja** [comment]
Oh gotcha, thanks a lot for pointing this out!

I don't think I will be updating the scraper for these attributes any time soon tho

but if I can be of any help please do reach out, it'll be my pleasure :D

**Comment by alizahidraja** [comment]
I also think the website doesn't have all of these but I can be wrong as I was mostly focused on the attributes that are currently in the CSV 

(a lot of repeating things that I am not liking but had to make a dataset)

**Comment by MohammedArab1** [comment]
Updated the project, will close this PR.

**Pull request closed without merging**
